apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-solr-pvc
spec:
{{/*  storageClassName: local-storage*/}}
{{/*  volumeName: ols4-solr-pv*/}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi

